/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.parser;

import compilador.node.*;
import compilador.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 0;
    }

    @Override
    public void caseTDoispontos(@SuppressWarnings("unused") TDoispontos node)
    {
        this.index = 1;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 2;
    }

    @Override
    public void caseTPontovirgula(@SuppressWarnings("unused") TPontovirgula node)
    {
        this.index = 3;
    }

    @Override
    public void caseTEParentese(@SuppressWarnings("unused") TEParentese node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDParentese(@SuppressWarnings("unused") TDParentese node)
    {
        this.index = 5;
    }

    @Override
    public void caseTEColchete(@SuppressWarnings("unused") TEColchete node)
    {
        this.index = 6;
    }

    @Override
    public void caseTDColchete(@SuppressWarnings("unused") TDColchete node)
    {
        this.index = 7;
    }

    @Override
    public void caseTEChave(@SuppressWarnings("unused") TEChave node)
    {
        this.index = 8;
    }

    @Override
    public void caseTDChave(@SuppressWarnings("unused") TDChave node)
    {
        this.index = 9;
    }

    @Override
    public void caseTMais(@SuppressWarnings("unused") TMais node)
    {
        this.index = 10;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 11;
    }

    @Override
    public void caseTMultiplicacao(@SuppressWarnings("unused") TMultiplicacao node)
    {
        this.index = 12;
    }

    @Override
    public void caseTDivisao(@SuppressWarnings("unused") TDivisao node)
    {
        this.index = 13;
    }

    @Override
    public void caseTPorcentagem(@SuppressWarnings("unused") TPorcentagem node)
    {
        this.index = 14;
    }

    @Override
    public void caseTResto(@SuppressWarnings("unused") TResto node)
    {
        this.index = 15;
    }

    @Override
    public void caseTAtribuicao(@SuppressWarnings("unused") TAtribuicao node)
    {
        this.index = 16;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 17;
    }

    @Override
    public void caseTDiferente(@SuppressWarnings("unused") TDiferente node)
    {
        this.index = 18;
    }

    @Override
    public void caseTMaiorq(@SuppressWarnings("unused") TMaiorq node)
    {
        this.index = 19;
    }

    @Override
    public void caseTMenorq(@SuppressWarnings("unused") TMenorq node)
    {
        this.index = 20;
    }

    @Override
    public void caseTMaiorigual(@SuppressWarnings("unused") TMaiorigual node)
    {
        this.index = 21;
    }

    @Override
    public void caseTMenorigual(@SuppressWarnings("unused") TMenorigual node)
    {
        this.index = 22;
    }

    @Override
    public void caseTE(@SuppressWarnings("unused") TE node)
    {
        this.index = 23;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 24;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 25;
    }

    @Override
    public void caseTEou(@SuppressWarnings("unused") TEou node)
    {
        this.index = 26;
    }

    @Override
    public void caseTPrograma(@SuppressWarnings("unused") TPrograma node)
    {
        this.index = 27;
    }

    @Override
    public void caseTInicio(@SuppressWarnings("unused") TInicio node)
    {
        this.index = 28;
    }

    @Override
    public void caseTFim(@SuppressWarnings("unused") TFim node)
    {
        this.index = 29;
    }

    @Override
    public void caseTVariavel(@SuppressWarnings("unused") TVariavel node)
    {
        this.index = 30;
    }

    @Override
    public void caseTInteiro(@SuppressWarnings("unused") TInteiro node)
    {
        this.index = 31;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 32;
    }

    @Override
    public void caseTCaractere(@SuppressWarnings("unused") TCaractere node)
    {
        this.index = 33;
    }

    @Override
    public void caseTEscreva(@SuppressWarnings("unused") TEscreva node)
    {
        this.index = 34;
    }

    @Override
    public void caseTLeia(@SuppressWarnings("unused") TLeia node)
    {
        this.index = 35;
    }

    @Override
    public void caseTConstante(@SuppressWarnings("unused") TConstante node)
    {
        this.index = 36;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 37;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 38;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 39;
    }

    @Override
    public void caseTFimse(@SuppressWarnings("unused") TFimse node)
    {
        this.index = 40;
    }

    @Override
    public void caseTEnquanto(@SuppressWarnings("unused") TEnquanto node)
    {
        this.index = 41;
    }

    @Override
    public void caseTFimenquanto(@SuppressWarnings("unused") TFimenquanto node)
    {
        this.index = 42;
    }

    @Override
    public void caseTPara(@SuppressWarnings("unused") TPara node)
    {
        this.index = 43;
    }

    @Override
    public void caseTFaca(@SuppressWarnings("unused") TFaca node)
    {
        this.index = 44;
    }

    @Override
    public void caseTFimpara(@SuppressWarnings("unused") TFimpara node)
    {
        this.index = 45;
    }

    @Override
    public void caseTCaso(@SuppressWarnings("unused") TCaso node)
    {
        this.index = 46;
    }

    @Override
    public void caseTAte(@SuppressWarnings("unused") TAte node)
    {
        this.index = 47;
    }

    @Override
    public void caseTRepita(@SuppressWarnings("unused") TRepita node)
    {
        this.index = 48;
    }

    @Override
    public void caseTFimrepita(@SuppressWarnings("unused") TFimrepita node)
    {
        this.index = 49;
    }

    @Override
    public void caseTRetorne(@SuppressWarnings("unused") TRetorne node)
    {
        this.index = 50;
    }

    @Override
    public void caseTPacote(@SuppressWarnings("unused") TPacote node)
    {
        this.index = 51;
    }

    @Override
    public void caseTNulo(@SuppressWarnings("unused") TNulo node)
    {
        this.index = 52;
    }

    @Override
    public void caseTTipo(@SuppressWarnings("unused") TTipo node)
    {
        this.index = 53;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 54;
    }

    @Override
    public void caseTComment(@SuppressWarnings("unused") TComment node)
    {
        this.index = 55;
    }

    @Override
    public void caseTCommentFim(@SuppressWarnings("unused") TCommentFim node)
    {
        this.index = 56;
    }

    @Override
    public void caseTCommentCorpo(@SuppressWarnings("unused") TCommentCorpo node)
    {
        this.index = 57;
    }

    @Override
    public void caseTEstrela(@SuppressWarnings("unused") TEstrela node)
    {
        this.index = 58;
    }

    @Override
    public void caseTBarra(@SuppressWarnings("unused") TBarra node)
    {
        this.index = 59;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 60;
    }
}
