/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ADiferenteExpLogRel extends PExpLogRel
{
    private PExpressao _expressao_;
    private TDiferente _diferente_;
    private PExpLogRel _expLogRel_;

    public ADiferenteExpLogRel()
    {
        // Constructor
    }

    public ADiferenteExpLogRel(
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") TDiferente _diferente_,
        @SuppressWarnings("hiding") PExpLogRel _expLogRel_)
    {
        // Constructor
        setExpressao(_expressao_);

        setDiferente(_diferente_);

        setExpLogRel(_expLogRel_);

    }

    @Override
    public Object clone()
    {
        return new ADiferenteExpLogRel(
            cloneNode(this._expressao_),
            cloneNode(this._diferente_),
            cloneNode(this._expLogRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADiferenteExpLogRel(this);
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public TDiferente getDiferente()
    {
        return this._diferente_;
    }

    public void setDiferente(TDiferente node)
    {
        if(this._diferente_ != null)
        {
            this._diferente_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._diferente_ = node;
    }

    public PExpLogRel getExpLogRel()
    {
        return this._expLogRel_;
    }

    public void setExpLogRel(PExpLogRel node)
    {
        if(this._expLogRel_ != null)
        {
            this._expLogRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao_)
            + toString(this._diferente_)
            + toString(this._expLogRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._diferente_ == child)
        {
            this._diferente_ = null;
            return;
        }

        if(this._expLogRel_ == child)
        {
            this._expLogRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._diferente_ == oldChild)
        {
            setDiferente((TDiferente) newChild);
            return;
        }

        if(this._expLogRel_ == oldChild)
        {
            setExpLogRel((PExpLogRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
