/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpressaoExp extends PExp
{
    private final LinkedList<PExpVirgula> _expVirgula_ = new LinkedList<PExpVirgula>();
    private PExpressao _expressao_;

    public AExpressaoExp()
    {
        // Constructor
    }

    public AExpressaoExp(
        @SuppressWarnings("hiding") List<?> _expVirgula_,
        @SuppressWarnings("hiding") PExpressao _expressao_)
    {
        // Constructor
        setExpVirgula(_expVirgula_);

        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new AExpressaoExp(
            cloneList(this._expVirgula_),
            cloneNode(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressaoExp(this);
    }

    public LinkedList<PExpVirgula> getExpVirgula()
    {
        return this._expVirgula_;
    }

    public void setExpVirgula(List<?> list)
    {
        for(PExpVirgula e : this._expVirgula_)
        {
            e.parent(null);
        }
        this._expVirgula_.clear();

        for(Object obj_e : list)
        {
            PExpVirgula e = (PExpVirgula) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expVirgula_.add(e);
        }
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expVirgula_)
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expVirgula_.remove(child))
        {
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpVirgula> i = this._expVirgula_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpVirgula) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
