/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExp extends PExp
{
    private PExpressaoLogica _expressaoLogica_;
    private final LinkedList<PExpVirgula> _expVirgula_ = new LinkedList<PExpVirgula>();

    public AExp()
    {
        // Constructor
    }

    public AExp(
        @SuppressWarnings("hiding") PExpressaoLogica _expressaoLogica_,
        @SuppressWarnings("hiding") List<?> _expVirgula_)
    {
        // Constructor
        setExpressaoLogica(_expressaoLogica_);

        setExpVirgula(_expVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AExp(
            cloneNode(this._expressaoLogica_),
            cloneList(this._expVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp(this);
    }

    public PExpressaoLogica getExpressaoLogica()
    {
        return this._expressaoLogica_;
    }

    public void setExpressaoLogica(PExpressaoLogica node)
    {
        if(this._expressaoLogica_ != null)
        {
            this._expressaoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLogica_ = node;
    }

    public LinkedList<PExpVirgula> getExpVirgula()
    {
        return this._expVirgula_;
    }

    public void setExpVirgula(List<?> list)
    {
        for(PExpVirgula e : this._expVirgula_)
        {
            e.parent(null);
        }
        this._expVirgula_.clear();

        for(Object obj_e : list)
        {
            PExpVirgula e = (PExpVirgula) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expVirgula_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoLogica_)
            + toString(this._expVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoLogica_ == child)
        {
            this._expressaoLogica_ = null;
            return;
        }

        if(this._expVirgula_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoLogica_ == oldChild)
        {
            setExpressaoLogica((PExpressaoLogica) newChild);
            return;
        }

        for(ListIterator<PExpVirgula> i = this._expVirgula_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpVirgula) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
