/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpressoesLogicoRelacionaisExpressaoRelacional extends PExpressaoRelacional
{
    private PExpLogRel _expLogRel_;

    public AExpressoesLogicoRelacionaisExpressaoRelacional()
    {
        // Constructor
    }

    public AExpressoesLogicoRelacionaisExpressaoRelacional(
        @SuppressWarnings("hiding") PExpLogRel _expLogRel_)
    {
        // Constructor
        setExpLogRel(_expLogRel_);

    }

    @Override
    public Object clone()
    {
        return new AExpressoesLogicoRelacionaisExpressaoRelacional(
            cloneNode(this._expLogRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressoesLogicoRelacionaisExpressaoRelacional(this);
    }

    public PExpLogRel getExpLogRel()
    {
        return this._expLogRel_;
    }

    public void setExpLogRel(PExpLogRel node)
    {
        if(this._expLogRel_ != null)
        {
            this._expLogRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogRel_ == child)
        {
            this._expLogRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogRel_ == oldChild)
        {
            setExpLogRel((PExpLogRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
