/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorQExpressaoRelacional extends PExpressaoRelacional
{
    private PExpressaoAritmetica _expressaoAritmetica_;
    private TMaiorQ _maiorQ_;
    private PExpressaoRelacional _expressaoRelacional_;

    public AMaiorQExpressaoRelacional()
    {
        // Constructor
    }

    public AMaiorQExpressaoRelacional(
        @SuppressWarnings("hiding") PExpressaoAritmetica _expressaoAritmetica_,
        @SuppressWarnings("hiding") TMaiorQ _maiorQ_,
        @SuppressWarnings("hiding") PExpressaoRelacional _expressaoRelacional_)
    {
        // Constructor
        setExpressaoAritmetica(_expressaoAritmetica_);

        setMaiorQ(_maiorQ_);

        setExpressaoRelacional(_expressaoRelacional_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorQExpressaoRelacional(
            cloneNode(this._expressaoAritmetica_),
            cloneNode(this._maiorQ_),
            cloneNode(this._expressaoRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorQExpressaoRelacional(this);
    }

    public PExpressaoAritmetica getExpressaoAritmetica()
    {
        return this._expressaoAritmetica_;
    }

    public void setExpressaoAritmetica(PExpressaoAritmetica node)
    {
        if(this._expressaoAritmetica_ != null)
        {
            this._expressaoAritmetica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoAritmetica_ = node;
    }

    public TMaiorQ getMaiorQ()
    {
        return this._maiorQ_;
    }

    public void setMaiorQ(TMaiorQ node)
    {
        if(this._maiorQ_ != null)
        {
            this._maiorQ_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQ_ = node;
    }

    public PExpressaoRelacional getExpressaoRelacional()
    {
        return this._expressaoRelacional_;
    }

    public void setExpressaoRelacional(PExpressaoRelacional node)
    {
        if(this._expressaoRelacional_ != null)
        {
            this._expressaoRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoAritmetica_)
            + toString(this._maiorQ_)
            + toString(this._expressaoRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoAritmetica_ == child)
        {
            this._expressaoAritmetica_ = null;
            return;
        }

        if(this._maiorQ_ == child)
        {
            this._maiorQ_ = null;
            return;
        }

        if(this._expressaoRelacional_ == child)
        {
            this._expressaoRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoAritmetica_ == oldChild)
        {
            setExpressaoAritmetica((PExpressaoAritmetica) newChild);
            return;
        }

        if(this._maiorQ_ == oldChild)
        {
            setMaiorQ((TMaiorQ) newChild);
            return;
        }

        if(this._expressaoRelacional_ == oldChild)
        {
            setExpressaoRelacional((PExpressaoRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
