/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorIgualExpressaoRelacional extends PExpressaoRelacional
{
    private PExpressaoAritmetica _expressaoAritmetica_;
    private TMaiorIgual _maiorIgual_;
    private PExpressaoRelacional _expressaoRelacional_;

    public AMaiorIgualExpressaoRelacional()
    {
        // Constructor
    }

    public AMaiorIgualExpressaoRelacional(
        @SuppressWarnings("hiding") PExpressaoAritmetica _expressaoAritmetica_,
        @SuppressWarnings("hiding") TMaiorIgual _maiorIgual_,
        @SuppressWarnings("hiding") PExpressaoRelacional _expressaoRelacional_)
    {
        // Constructor
        setExpressaoAritmetica(_expressaoAritmetica_);

        setMaiorIgual(_maiorIgual_);

        setExpressaoRelacional(_expressaoRelacional_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorIgualExpressaoRelacional(
            cloneNode(this._expressaoAritmetica_),
            cloneNode(this._maiorIgual_),
            cloneNode(this._expressaoRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorIgualExpressaoRelacional(this);
    }

    public PExpressaoAritmetica getExpressaoAritmetica()
    {
        return this._expressaoAritmetica_;
    }

    public void setExpressaoAritmetica(PExpressaoAritmetica node)
    {
        if(this._expressaoAritmetica_ != null)
        {
            this._expressaoAritmetica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoAritmetica_ = node;
    }

    public TMaiorIgual getMaiorIgual()
    {
        return this._maiorIgual_;
    }

    public void setMaiorIgual(TMaiorIgual node)
    {
        if(this._maiorIgual_ != null)
        {
            this._maiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorIgual_ = node;
    }

    public PExpressaoRelacional getExpressaoRelacional()
    {
        return this._expressaoRelacional_;
    }

    public void setExpressaoRelacional(PExpressaoRelacional node)
    {
        if(this._expressaoRelacional_ != null)
        {
            this._expressaoRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoAritmetica_)
            + toString(this._maiorIgual_)
            + toString(this._expressaoRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoAritmetica_ == child)
        {
            this._expressaoAritmetica_ = null;
            return;
        }

        if(this._maiorIgual_ == child)
        {
            this._maiorIgual_ = null;
            return;
        }

        if(this._expressaoRelacional_ == child)
        {
            this._expressaoRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoAritmetica_ == oldChild)
        {
            setExpressaoAritmetica((PExpressaoAritmetica) newChild);
            return;
        }

        if(this._maiorIgual_ == oldChild)
        {
            setMaiorIgual((TMaiorIgual) newChild);
            return;
        }

        if(this._expressaoRelacional_ == oldChild)
        {
            setExpressaoRelacional((PExpressaoRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
