/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorIgualExpLogRel extends PExpLogRel
{
    private PExpressao _expressao_;
    private TMaiorIgual _maiorIgual_;
    private PExpLogRel _expLogRel_;

    public AMaiorIgualExpLogRel()
    {
        // Constructor
    }

    public AMaiorIgualExpLogRel(
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") TMaiorIgual _maiorIgual_,
        @SuppressWarnings("hiding") PExpLogRel _expLogRel_)
    {
        // Constructor
        setExpressao(_expressao_);

        setMaiorIgual(_maiorIgual_);

        setExpLogRel(_expLogRel_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorIgualExpLogRel(
            cloneNode(this._expressao_),
            cloneNode(this._maiorIgual_),
            cloneNode(this._expLogRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorIgualExpLogRel(this);
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public TMaiorIgual getMaiorIgual()
    {
        return this._maiorIgual_;
    }

    public void setMaiorIgual(TMaiorIgual node)
    {
        if(this._maiorIgual_ != null)
        {
            this._maiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorIgual_ = node;
    }

    public PExpLogRel getExpLogRel()
    {
        return this._expLogRel_;
    }

    public void setExpLogRel(PExpLogRel node)
    {
        if(this._expLogRel_ != null)
        {
            this._expLogRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao_)
            + toString(this._maiorIgual_)
            + toString(this._expLogRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._maiorIgual_ == child)
        {
            this._maiorIgual_ = null;
            return;
        }

        if(this._expLogRel_ == child)
        {
            this._expLogRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._maiorIgual_ == oldChild)
        {
            setMaiorIgual((TMaiorIgual) newChild);
            return;
        }

        if(this._expLogRel_ == oldChild)
        {
            setExpLogRel((PExpLogRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
