/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorQOperadorRelacional extends POperadorRelacional
{
    private TMaiorQ _maiorQ_;

    public AMaiorQOperadorRelacional()
    {
        // Constructor
    }

    public AMaiorQOperadorRelacional(
        @SuppressWarnings("hiding") TMaiorQ _maiorQ_)
    {
        // Constructor
        setMaiorQ(_maiorQ_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorQOperadorRelacional(
            cloneNode(this._maiorQ_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorQOperadorRelacional(this);
    }

    public TMaiorQ getMaiorQ()
    {
        return this._maiorQ_;
    }

    public void setMaiorQ(TMaiorQ node)
    {
        if(this._maiorQ_ != null)
        {
            this._maiorQ_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQ_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._maiorQ_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._maiorQ_ == child)
        {
            this._maiorQ_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._maiorQ_ == oldChild)
        {
            setMaiorQ((TMaiorQ) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
