/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AManorQOperadorRelacional extends POperadorRelacional
{
    private TMenorQ _menorQ_;

    public AManorQOperadorRelacional()
    {
        // Constructor
    }

    public AManorQOperadorRelacional(
        @SuppressWarnings("hiding") TMenorQ _menorQ_)
    {
        // Constructor
        setMenorQ(_menorQ_);

    }

    @Override
    public Object clone()
    {
        return new AManorQOperadorRelacional(
            cloneNode(this._menorQ_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManorQOperadorRelacional(this);
    }

    public TMenorQ getMenorQ()
    {
        return this._menorQ_;
    }

    public void setMenorQ(TMenorQ node)
    {
        if(this._menorQ_ != null)
        {
            this._menorQ_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorQ_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menorQ_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menorQ_ == child)
        {
            this._menorQ_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menorQ_ == oldChild)
        {
            setMenorQ((TMenorQ) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
