/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMenorIgualExpLogRel extends PExpLogRel
{
    private PExpressao _expressao_;
    private TMenorIgual _menorIgual_;
    private PExpLogRel _expLogRel_;

    public AMenorIgualExpLogRel()
    {
        // Constructor
    }

    public AMenorIgualExpLogRel(
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") TMenorIgual _menorIgual_,
        @SuppressWarnings("hiding") PExpLogRel _expLogRel_)
    {
        // Constructor
        setExpressao(_expressao_);

        setMenorIgual(_menorIgual_);

        setExpLogRel(_expLogRel_);

    }

    @Override
    public Object clone()
    {
        return new AMenorIgualExpLogRel(
            cloneNode(this._expressao_),
            cloneNode(this._menorIgual_),
            cloneNode(this._expLogRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorIgualExpLogRel(this);
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public TMenorIgual getMenorIgual()
    {
        return this._menorIgual_;
    }

    public void setMenorIgual(TMenorIgual node)
    {
        if(this._menorIgual_ != null)
        {
            this._menorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorIgual_ = node;
    }

    public PExpLogRel getExpLogRel()
    {
        return this._expLogRel_;
    }

    public void setExpLogRel(PExpLogRel node)
    {
        if(this._expLogRel_ != null)
        {
            this._expLogRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao_)
            + toString(this._menorIgual_)
            + toString(this._expLogRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._menorIgual_ == child)
        {
            this._menorIgual_ = null;
            return;
        }

        if(this._expLogRel_ == child)
        {
            this._expLogRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._menorIgual_ == oldChild)
        {
            setMenorIgual((TMenorIgual) newChild);
            return;
        }

        if(this._expLogRel_ == oldChild)
        {
            setExpLogRel((PExpLogRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
