/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AParenteseLogicaTermoLogico extends PTermoLogico
{
    private TEParentese _eParentese_;
    private PExpressaoLogica _expressaoLogica_;
    private TDParentese _dParentese_;

    public AParenteseLogicaTermoLogico()
    {
        // Constructor
    }

    public AParenteseLogicaTermoLogico(
        @SuppressWarnings("hiding") TEParentese _eParentese_,
        @SuppressWarnings("hiding") PExpressaoLogica _expressaoLogica_,
        @SuppressWarnings("hiding") TDParentese _dParentese_)
    {
        // Constructor
        setEParentese(_eParentese_);

        setExpressaoLogica(_expressaoLogica_);

        setDParentese(_dParentese_);

    }

    @Override
    public Object clone()
    {
        return new AParenteseLogicaTermoLogico(
            cloneNode(this._eParentese_),
            cloneNode(this._expressaoLogica_),
            cloneNode(this._dParentese_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParenteseLogicaTermoLogico(this);
    }

    public TEParentese getEParentese()
    {
        return this._eParentese_;
    }

    public void setEParentese(TEParentese node)
    {
        if(this._eParentese_ != null)
        {
            this._eParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eParentese_ = node;
    }

    public PExpressaoLogica getExpressaoLogica()
    {
        return this._expressaoLogica_;
    }

    public void setExpressaoLogica(PExpressaoLogica node)
    {
        if(this._expressaoLogica_ != null)
        {
            this._expressaoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLogica_ = node;
    }

    public TDParentese getDParentese()
    {
        return this._dParentese_;
    }

    public void setDParentese(TDParentese node)
    {
        if(this._dParentese_ != null)
        {
            this._dParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dParentese_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eParentese_)
            + toString(this._expressaoLogica_)
            + toString(this._dParentese_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eParentese_ == child)
        {
            this._eParentese_ = null;
            return;
        }

        if(this._expressaoLogica_ == child)
        {
            this._expressaoLogica_ = null;
            return;
        }

        if(this._dParentese_ == child)
        {
            this._dParentese_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eParentese_ == oldChild)
        {
            setEParentese((TEParentese) newChild);
            return;
        }

        if(this._expressaoLogica_ == oldChild)
        {
            setExpressaoLogica((PExpressaoLogica) newChild);
            return;
        }

        if(this._dParentese_ == oldChild)
        {
            setDParentese((TDParentese) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
