/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ARelacionalExpressaoRelacional extends PExpressaoRelacional
{
    private PExpressao _expressao_;
    private POperadorRelacional _operadorRelacional_;
    private PExpressaoRelacional _expressaoRelacional_;

    public ARelacionalExpressaoRelacional()
    {
        // Constructor
    }

    public ARelacionalExpressaoRelacional(
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") POperadorRelacional _operadorRelacional_,
        @SuppressWarnings("hiding") PExpressaoRelacional _expressaoRelacional_)
    {
        // Constructor
        setExpressao(_expressao_);

        setOperadorRelacional(_operadorRelacional_);

        setExpressaoRelacional(_expressaoRelacional_);

    }

    @Override
    public Object clone()
    {
        return new ARelacionalExpressaoRelacional(
            cloneNode(this._expressao_),
            cloneNode(this._operadorRelacional_),
            cloneNode(this._expressaoRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacionalExpressaoRelacional(this);
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public POperadorRelacional getOperadorRelacional()
    {
        return this._operadorRelacional_;
    }

    public void setOperadorRelacional(POperadorRelacional node)
    {
        if(this._operadorRelacional_ != null)
        {
            this._operadorRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operadorRelacional_ = node;
    }

    public PExpressaoRelacional getExpressaoRelacional()
    {
        return this._expressaoRelacional_;
    }

    public void setExpressaoRelacional(PExpressaoRelacional node)
    {
        if(this._expressaoRelacional_ != null)
        {
            this._expressaoRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao_)
            + toString(this._operadorRelacional_)
            + toString(this._expressaoRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._operadorRelacional_ == child)
        {
            this._operadorRelacional_ = null;
            return;
        }

        if(this._expressaoRelacional_ == child)
        {
            this._expressaoRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._operadorRelacional_ == oldChild)
        {
            setOperadorRelacional((POperadorRelacional) newChild);
            return;
        }

        if(this._expressaoRelacional_ == oldChild)
        {
            setExpressaoRelacional((PExpressaoRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
