/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TComentarioAninhadoCorpo extends Token
{
    public TComentarioAninhadoCorpo(String text)
    {
        setText(text);
    }

    public TComentarioAninhadoCorpo(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComentarioAninhadoCorpo(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComentarioAninhadoCorpo(this);
    }
}
