/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TFimrepita extends Token
{
    public TFimrepita()
    {
        super.setText("fim repita");
    }

    public TFimrepita(int line, int pos)
    {
        super.setText("fim repita");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimrepita(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimrepita(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimrepita text.");
    }
}
