/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TInterromper extends Token
{
    public TInterromper()
    {
        super.setText("interromper");
    }

    public TInterromper(int line, int pos)
    {
        super.setText("interromper");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInterromper(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInterromper(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInterromper text.");
    }
}
