/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TNulo extends Token
{
    public TNulo()
    {
        super.setText("nulo");
    }

    public TNulo(int line, int pos)
    {
        super.setText("nulo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNulo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNulo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNulo text.");
    }
}
