/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TPacote extends Token
{
    public TPacote()
    {
        super.setText("pacote");
    }

    public TPacote(int line, int pos)
    {
        super.setText("pacote");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPacote(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPacote(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPacote text.");
    }
}
